plugins {
    id 'com.android.application'
}

android {
    namespace 'com.retrosnake'
    compileSdk 34

    defaultConfig {
        applicationId "com.retrosnake.game"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar'])
}

